# .goreleaser.yml
release:
  github:
    owner: openaq
    name: openaq-cli

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    dir: .
    main: .
    binary: openaq
    flags:
      - -trimpath
    ldflags:
      - -X github.com/openaq/openaq-cli/cmd/version.Version={{.Version}}
      - -s -w 

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'


# Homebrew
brews:
  - repository:
      owner: openaq
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://github.com/openaq/openaq-cli
    description: Official Command Line Interface for OpenAQ. Get your API key here -> https://api.openaq.org/register
    license: MIT
    test: |
      system "#{bin}/openaq-cli -v"

# Scoop
scoops:
  - repository:
      owner: openaq
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: bucket
    homepage: https://github.com/openaq/openaq-cli
    description: |
     Official Command Line Interface for OpenAQ. Get your API key here -> https://api.openaq.org/register
    license: MIT
