# .goreleaser.yml
# release:
#   github:
#     owner: openaq
#     name: openaq-cli

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    dir: .
    main: .
    binary: openaq
    flags:
      - -trimpath
    ldflags:
      - -X github.com/openaq/openaq-cli/cmd/version.Version={{.Version}}
      - -s -w 

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

# Homebrew
brews:
  - repository:
      owner: openaq
      name: homebrew-tap
    folder: Formula
    goarm: "7"
    homepage: https://openaq.org
    description: Official Command Line Interface for OpenAQ.
    license: MIT
    test: |
      system "#{bin}/goreleaser -v"
    # dependencies:
    #   - name: go
    #     type: optional
    #   - name: git
    # conflicts:
    #   - goreleaser-pro
    # extra_install: |-
    #   bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    #   zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    #   fish_completion.install "completions/goreleaser.fish"
    #   man1.install "manpages/goreleaser.1.gz"

