# .goreleaser.yml
# release:
#   github:
#     owner: openaq
#     name: openaq-cli

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    dir: .
    main: .
    binary: openaq
    flags:
      - -trimpath
    ldflags:
      - -X github.com/openaq/openaq-cli/cmd/version.Version={{.Version}}
      - -s -w 

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'


# Homebrew
brews:
  - repository:
      owner: openaq
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://openaq.org
    description: Official Command Line Interface for OpenAQ. Get your API key here -> https://api.openaq.org/register
    license: MIT
    test: |
      system "#{bin}/openaq-cli -v"
    # extra_install: |-
    #   bash_completion.install "completions/openaq.bash" => "openaq"
    #   zsh_completion.install "completions/openaq.zsh" => "_openaq"
    #   fish_completion.install "completions/openaq.fish"
    #   man1.install "manpages/openaq.1.gz"


scoops:
  - repository:
      owner: openaq
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: bucket
    homepage: https://openaq.org
    description: |
     Official Command Line Interface for OpenAQ. Get your API key here -> https://api.openaq.org/register
    license: MIT

# archives needed for winget & chocolatey
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE.md
      - completions/*
      - manpages/*

# Chocolatey
chocolateys:
  -
    name: openaq
    ids:
      - openaq-cli
    owners: OpenAQ
    title: OpenAQ CLI
    authors: OpenAQ
    project_url: https://github.com/openaq/openaq-cli
    url_template: "https://github.com/openaq/openaq-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    icon_url: 'https://github.com/openaq/openaq.org/blob/main/static/favicon-96x96.png'
    copyright: 2023 OpenAQ
    license_url: https://github.com/openaq/openaq-cli/blob/main/LICENSE.md
    require_license_acceptance: false
    project_source_url: https://github.com/openaq/openaq-cli
    docs_url: https://github.com/openaq/openaq-cli/blob/main/README.md
    bug_tracker_url: https://github.com/openaq/openaq-cli/issues
    tags: "openaq, air quality, cli"
    summary: Official Command Line Interface for OpenAQ.
    description: |
      OpenAQ CLI is the official command-line tool to interact with the OpenAQ API. Get your API key here -> https://api.openaq.org/register
    release_notes: "https://github.com/openaq/openaq-cli/releases/tag/v{{ .Version }}"
    api_key: '{{ .Env.CHOCOLATEY_API_KEY }}'
    source_repo: "https://push.chocolatey.org/"
    skip_publish: false


# winget:
#   - name: openaq
#     publisher: openaq
#     license: MIT
#     homepage: https://openaq.org
#     short_description: Official Command Line Interface for OpenAQ.
#     repository:
#       owner: openaq
#       name: winget-pkgs
#       token: "{{ .Env.TAP_GITHUB_TOKEN }}"
#       branch: main        # "openaq-cli-{{.Version}}"
      # pull_request: # create a PR for wingets main repo
      #   enabled: true
      #   draft: true
      #   base:
      #     owner: microsoft
      #     name: winget-pkgs
      #     branch: master

# aurs:
#   - homepage: https://openaq.org
#     description: Official Command Line Interface for OpenAQ.
#     maintainers:
#       - "Dev <dev@openaq.org>"
#     license: MIT
#     private_key: "{{ .Env.AUR_KEY }}" # needed
#     git_url: "ssh://aur@aur.archlinux.org/openaq-cli-bin.git"
#     package: |-
#       # bin
#       install -Dm755 "./openaq-cli" "${pkgdir}/usr/bin/openaq-cli"

#       # license
#       install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/openaq-cli/LICENSE"

#       # completions
#       mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
#       mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
#       mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
#       install -Dm644 "./completions/openaq-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/openaq-cli"
#       install -Dm644 "./completions/openaq-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_openaq-cli"
#       install -Dm644 "./completions/openaq-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/openaq-cli.fish"

#       # man pages
#       install -Dm644 "./manpages/goreleaser.1.gz" "${pkgdir}/usr/share/man/man1/openaq-cli.1.gz"

# snapcrafts:
#   - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     summary: Official Command Line Interface for OpenAQ.
#     description: |
#       write a description here.
#     grade: stable
#     confinement: classic
#     publish: true
#     disable: "{{ if .IsNightly }}true{{ end }}"

# nfpms:
#   - file_name_template: "{{ .ConventionalFileName }}"
#     id: packages
#     homepage: https://openaq.org
#     description: |-
#       Official Command Line Interface for OpenAQ.
#     maintainer: Dev <dev@openaq.org>
#     license: MIT
#     vendor: OpenAQ
#     bindir: /usr/bin
#     section: utils
#     contents:
#       - src: ./completions/openaq-cli.bash
#         dst: /usr/share/bash-completion/completions/openaq-cli
#         file_info:
#           mode: 0644
#       - src: ./completions/openaq-cli.fish
#         dst: /usr/share/fish/vendor_completions.d/openaq-cli.fish
#         file_info:
#           mode: 0644
#       - src: ./completions/openaq-cli.zsh
#         dst: /usr/share/zsh/vendor-completions/_openaq-cli
#         file_info:
#           mode: 0644
#       - src: ./manpages/openaq-cli.1.gz
#         dst: /usr/share/man/man1/openaq-cli.1.gz
#         file_info:
#           mode: 0644
#       - src: ./LICENSE.md
#         dst: /usr/share/doc/openaq-cli/copyright
#         file_info:
#           mode: 0644
#     formats:
#       - apk
#       - deb
#       - rpm
#       - archlinux
#     dependencies:
#       - git
#     recommends:
#       - golang
#     deb:
#       lintian_overrides:
#         - statically-linked-binary
#         - changelog-file-missing-in-native-package
