# .goreleaser.yml
# release:
#   github:
#     owner: openaq
#     name: openaq-cli

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: freebsd
        goarch: arm
    dir: .
    main: .
    binary: openaq
    flags:
      - -trimpath
    ldflags:
      - -X github.com/openaq/openaq-cli/cmd/version.Version={{.Version}}
      - -s -w 

checksum:
  algorithm: sha256
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

# Homebrew
brews:
  - repository:
      owner: openaq
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: Formula
    goarm: "7"
    homepage: https://openaq.org
    description: Official Command Line Interface for OpenAQ.
    license: MIT
    test: |
      system "#{bin}/openaq-cli -v"
    # dependencies:
    #   - name: go
    #     type: optional
    #   - name: git
    # conflicts:
    #   - goreleaser-pro
    # extra_install: |-
    #   bash_completion.install "completions/goreleaser.bash" => "goreleaser"
    #   zsh_completion.install "completions/goreleaser.zsh" => "_goreleaser"
    #   fish_completion.install "completions/goreleaser.fish"
    #   man1.install "manpages/goreleaser.1.gz"

scoops:
  - repository:
      owner: openaq
      name: scoop-bucket
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    folder: bucket
    homepage: https://openaq.org
    description: Official Command Line Interface for OpenAQ.
    license: MIT


# winget:
#   - name: openaq
#     publisher: openaq
#     license: MIT
#     homepage: https://openaq.org
#     short_description: Official Command Line Interface for OpenAQ.
#     repository:
#       owner: openaq
#       name: winget-pkgs
#       branch: "openaq-cli-{{.Version}}"
#       pull_request:
#         enabled: true
#         draft: true
#         base:
#           owner: microsoft
#           name: winget-pkgs
#           branch: master

# aurs:
#   - homepage: https://openaq.org
#     description: Official Command Line Interface for OpenAQ.
#     maintainers:
#       - "Dev <dev@openaq.org>"
#     license: MIT
#     private_key: "{{ .Env.AUR_KEY }}" # needed
#     git_url: "ssh://aur@aur.archlinux.org/openaq-cli-bin.git"
#     package: |-
#       # bin
#       install -Dm755 "./openaq-cli" "${pkgdir}/usr/bin/openaq-cli"

#       # license
#       install -Dm644 "./LICENSE.md" "${pkgdir}/usr/share/licenses/openaq-cli/LICENSE"

#       # completions
#       mkdir -p "${pkgdir}/usr/share/bash-completion/completions/"
#       mkdir -p "${pkgdir}/usr/share/zsh/site-functions/"
#       mkdir -p "${pkgdir}/usr/share/fish/vendor_completions.d/"
#       install -Dm644 "./completions/openaq-cli.bash" "${pkgdir}/usr/share/bash-completion/completions/openaq-cli"
#       install -Dm644 "./completions/openaq-cli.zsh" "${pkgdir}/usr/share/zsh/site-functions/_openaq-cli"
#       install -Dm644 "./completions/openaq-cli.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/openaq-cli.fish"

#       # man pages
#       install -Dm644 "./manpages/goreleaser.1.gz" "${pkgdir}/usr/share/man/man1/openaq-cli.1.gz"

# snapcrafts:
#   - name_template: "{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
#     summary: Official Command Line Interface for OpenAQ.
#     description: |
#       write a description here.
#     grade: stable
#     confinement: classic
#     publish: true
#     disable: "{{ if .IsNightly }}true{{ end }}"

# nfpms:
#   - file_name_template: "{{ .ConventionalFileName }}"
#     id: packages
#     homepage: https://openaq.org
#     description: |-
#       Official Command Line Interface for OpenAQ.
#     maintainer: Dev <dev@openaq.org>
#     license: MIT
#     vendor: OpenAQ
#     bindir: /usr/bin
#     section: utils
#     contents:
#       - src: ./completions/openaq-cli.bash
#         dst: /usr/share/bash-completion/completions/openaq-cli
#         file_info:
#           mode: 0644
#       - src: ./completions/openaq-cli.fish
#         dst: /usr/share/fish/vendor_completions.d/openaq-cli.fish
#         file_info:
#           mode: 0644
#       - src: ./completions/openaq-cli.zsh
#         dst: /usr/share/zsh/vendor-completions/_openaq-cli
#         file_info:
#           mode: 0644
#       - src: ./manpages/openaq-cli.1.gz
#         dst: /usr/share/man/man1/openaq-cli.1.gz
#         file_info:
#           mode: 0644
#       - src: ./LICENSE.md
#         dst: /usr/share/doc/openaq-cli/copyright
#         file_info:
#           mode: 0644
#     formats:
#       - apk
#       - deb
#       - rpm
#       - archlinux
#     dependencies:
#       - git
#     recommends:
#       - golang
#     deb:
#       lintian_overrides:
#         - statically-linked-binary
#         - changelog-file-missing-in-native-package
